### ISSUE TITLE
[Question] Does this plugin work in Klipper?

### ISSUE THREAD

**Issue by kennethpangky** [bradcfisher/OctoPrint-ExcludeRegionPlugin#17]
Just curious. It works well in Marlin but does it work in Klipper?

**Comment by bradcfisher** [comment]
That is an interesting question.  All of my development and testing was done using a Marlin-based printer, though that doesn't necessarily mean that it wouldn't work with Klipper.  As long as the Gcode commands interpreted by the plugin follow the same semantics as Marlin uses, there's a good chance it may work.  Based on what I see in the [Klipper GCode documentation](https://github.com/KevinOConnor/klipper/blob/master/docs/G-Codes.md) on GitHub, I believe that there would be little difference between the two for the relevant commands.

The following Gcode commands are currently interpreted by the plugin, and all others are simply passed through.

G0 [X Y Z E F] - Linear move
G1 - same as G0
G2 [E F R X Y Z] or G2 [E F I J X Y Z] - Arcs (does not seem to be supported by Klipper)
G3 - same as G2
G4 - dwell (ignored when excluding)
G10 - Firmware retract (does not seem to be supported by Klipper)
G11 - Firmware unretract (does not seem to be supported by Klipper)
G20 - Set units to inches (does not seem to be supported by Klipper)
G21 - Set units to mm (does not seem to be supported by Klipper)
G28 [X Y Z] - Home axis
G90 - Absolute positioning
G91 - Relative positioning
G92 [X Y Z E] - Set current position
M204 - Set accelerations (tracked while excluding, but not processed until after exiting an excluded area)
M205 - Set advanced settings (tracked while excluding, but not processed until after exiting an excluded area) (does not seem to be supported by Klipper)
M206 [P T X Y Z] - Set home offsets (supported by Klipper, but recommended to use Klipper's SET_GCODE_OFFSET "extended" GCode command instead)

As long as M206 is used instead of SET_GCODE_OFFSET, it looks like everything would probably work as expected.  

If you do happen to try it, I'd be very interested to know your results.  There would some risk involved , and I can't guarantee that it would work correctly (potentially resulting in damage to your printer), but it seems like it could be an interesting experiment.

**Comment by kennethpangky** [comment]
Thanks for the reply. Was hoping to see if someone had any experience before I took the leap to Klipper, but I did it anyway. 

So I tested it, it works! However had one issue that's mostly not Klipper related - it tends to pause over print objects at times, which causes it to form blobs on top of prints, and then prints are knocked over when the nozzle hits them later on. Not sure how this could be solved, but something I should mention anyway.

But Klipper + ExcludeRegion works! 💃

**Comment by bradcfisher** [comment]
That's good news!  Nice to hear that it works with Klipper, and I appreciate the chance you took to give it a try.

Those blobs you mentioned may be due to delays caused by excessive logging that the current version may be doing.  Take a look at the discussion on #9.  Perhaps the workaround to tweak the logging level for the plugin suggested there may help.  I do have some updates in the works to address that as well as add some additional functionality, but have had very little time lately to complete them.
